### ISSUE TITLE
RuntimeError with input size

### ISSUE THREAD

**Issue by SDeepDreamS** [LUSSeg/ImageNetSegModel#2]
Hello, 

Thank you for your outstanding research. 
I met some problems when I tried the following code:

> python -m torch.distributed.launch --nproc_per_node=1 main_segfinetune.py \
> --accum_iter 8 \
> --batch_size 32 \
> --model vit_small_patch16 \
> --finetune sere_finetuned_vit_small_ep100.pth \
> --epochs 100 \
> --nb_classes 920 \
> --blr 5e-4 --layer_decay 0.50 \
> --weight_decay 0.05 --drop_path 0.1  \
> --data_path ${IMAGENETS_DIR} \
> --output_dir ${OUTPATH} \
> --dist_eval

I got a RuntimeError like this:

> Traceback (most recent call last):
>   File "main_segfinetune.py", line 417, in <module>
>     main(args)
>   File "main_segfinetune.py", line 359, in main
>     train_stats = train_one_epoch(model,
>   File "/home/ImageNetSegModel/engine_segfinetune.py", line 59, in train_one_epoch
>     outputs = model(samples)
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 552, in forward
>     x = self.forward_head(x)
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 545, in forward_head
>     x = self.fc_norm(x)
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 190, in forward
>     return F.layer_norm(
>   File "/home/ImageNetSegModel/Segenv/lib/python3.8/site-packages/torch/nn/functional.py", line 2517, in layer_norm
>     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
> RuntimeError: Given normalized_shape=[384], expected input with shape [*, 384], but got input of size[32, 14, 14]

This seems to be a problem with input size. May I ask if I have missed any steps that could lead to this issue, or is there anything that needs to be corrected when reproducing the experiment? 

Thank you for taking the time to respond!

**Comment by gasvn** [comment]
It seems like a timm version issue. You can try do downgrade the timm to 0.3.2

**Comment by SDeepDreamS** [comment]
Hello,

After I downgraded the timm, it showed this problem: No module named 'timm.models.convnext'.
Actually, I met this problem in the beginning, so I upgraded the timm module. 

Could you give me any advice to solve it? Thank you very much!

**Comment by lzyhha** [comment]
We have update the codes and now the codes support latest timm, e.g., 0.6.12.

**Comment by SDeepDreamS** [comment]
It works now. Thanks a lot!

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.
